# Generated by Django 4.2.2 on 2023-06-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contributor_user_issue_assignee_issue_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.issue'),
        ),
    ]
