# Generated by Django 4.2.2 on 2023-06-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'BACK-END'), ('front-end', 'FRONT-END'), ('iOS', 'iOS'), ('Android', 'Android')], default='Please choose the type', max_length=10),
        ),
    ]
