# Generated by Django 4.2.2 on 2023-06-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('author', 'AUTHOR'), ('contributor', 'CONTRIBUTOR')], max_length=11),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'LOW'), ('moderate', 'MODERATE'), ('high', 'HIGH')], max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to_do', 'TO DO'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], max_length=11),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('bug', 'BUG'), ('improvement', 'IMPROVEMENT'), ('task', 'TASK')], max_length=11),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'BACK-END'), ('front-end', 'FRONT-END'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=9),
        ),
    ]
