# Generated by Django 4.2.2 on 2023-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=11),
        ),
    ]
